openapi: 3.0.1
info:
  title: Roster Calculator API
  description: |-
    The roster calculator calculates the best roster for given shifts based on the availability and constraints of given people.

  contact:
    email: pascal.keimel@apwp.de
  version: 0.0.1
servers:
  - url: https://roster-calculator.de/v1
paths:
  /roster:
    post:
      summary: create a new roster for calculation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preconditions'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roster'
        '422':
          description: Validation exception
  /roster/{rosterCalculationId}:
    get:
      summary: get status of a roster calculation with result if already completed
      parameters:
        - name: rosterCalculationId
          in: path
          description: ID of calculation to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Roster'
        '404':
          description: Invalid id supplied
  /rating:
    post:
      summary: calculate rating for given preconditions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preconditions'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '422':
          description: Validation exception
components:
  schemas:
    Preconditions:
      type: object
      required:
        - locations
        - shifts
        - people
      properties:
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'
        shifts:
          type: array
          items:
            $ref: '#/components/schemas/Shift'
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        ratingPointWeightings:
          $ref: '#/components/schemas/RatingPointWeightings'
    Roster:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
        status:
          type: string
          enum:
            - not_started
            - in_progress
            - completed
        createdAt:
          type: string
          format: date-time
        assignments:
          type: array
          items:
            type: object
            required:
              - shiftId
              - personIds
            properties:
              shiftId:
                type: string
              personIds:
                type: array
                items:
                  type: string
        personalResults:
          type: array
          items:
            type: object
            required:
              - personId
              - calculatedShifts
            properties:
              personId:
                type: string
              calculatedShifts:
                type: integer
        rating:
          $ref: '#/components/schemas/Rating'
        counter:
          type: integer
        isTimeout:
          type: boolean
    Shift:
      type: object
      required:
        - id
        - date
        - daytime
        - person_ids
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        daytime:
          type: string
          enum:
            - all
            - am
            - pm
        personIds:
          type: array
          items:
            type: string
        locationId:
          type: string
    Person:
      type: object
      required:
        - id
        - gender
        - constraints
        - availabilities
      properties:
        id:
          type: string
        gender:
          type: string
          enum:
            - diverse
            - female
            - male
        constraints:
          type: object
          required:
            - wishedShiftsPerMonth
            - maxShiftsPerMonth
            - maxShiftsPerDay
            - targetShifts
          properties:
            wishedShiftsPerMonth:
              type: integer
            maxShiftsPerMonth:
              type: integer
            maxShiftsPerDay:
              type: integer
            maxShiftsPerWeek:
              type: integer
            targetShifts:
              type: integer
            locationPreferences:
              type: array
              items:
                type: object
                required:
                  - locationId
                  - points
                properties:
                  locationId:
                    type: string
                  points:
                    type: integer
            locationPreferenceDefaultPoints:
              type: integer
            blockedPeopleIds:
              type: array
              items:
                type: string
        availabilities:
          type: array
          items:
            type: object
            required:
              - date
              - daytime
              - availability
            properties:
              date:
                type: string
                format: date
              daytime:
                type: string
                enum:
                  - am
                  - pm
              availability:
                type: string
                enum:
                  - maybe
                  - no
                  - yes
    Location:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        blockedPeopleIds:
          type: array
          items:
            type: string
    RatingPointWeightings:
      type: object
      required:
        - pointsPerMissingPerson
        - pointsPerMaxPerWeekExceeded
        - pointsPerMaybePerson
        - pointsPerTargetShiftsMissed
      properties:
        pointsPerMissingPerson:
          type: integer
          minimum: 0
          maximum: 1000
        pointsPerMaxPerWeekExceeded:
          type: integer
          minimum: 0
          maximum: 1000
        pointsPerMaybePerson:
          type: integer
          minimum: 0
          maximum: 1000
        pointsPerTargetShiftsMissed:
          type: integer
          minimum: 0
          maximum: 1000
    Rating:
      type: object
      required:
        - missingPerson
        - maybePerson
        - targetShifts
        - maxPerWeek
        - locationPreferences
        - total
      properties:
        missingPerson:
          type: integer
        maybePerson:
          type: integer
        targetShifts:
          type: integer
        maxPerWeek:
          type: integer
        locationPreferences:
          type: integer
        total:
          type: integer
